---
# Github Actions workflow to check and build StanHeaders and RStan
# yamllint disable rule:line-length

name: R-CMD-check

'on':
  push:
    branches:
      - develop
      - experimental
      - StanHeaders_*
      - workflow-check
  pull_request:
    branches:
      - develop
      - experimental
      - StanHeaders_*

jobs:
  R-CMD-check:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: true
      matrix:
        config:
          - {os: macOS-latest, r: 'release'}
          - {os: macOS-latest, r: 'oldrel'}
          - {os: windows-latest, r: 'release'}
          - {os: windows-latest, r: 'oldrel'}
          - {os: ubuntu-20.04, r: 'devel'}
          - {os: ubuntu-20.04, r: 'release'}
          - {os: ubuntu-20.04, r: 'oldrel'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: StanHeaders
          extra-packages: any::rcmdcheck, local::.

      - uses: r-lib/actions/check-r-package@v2
        with:
          working-directory: StanHeaders
        env:
          _R_CHECK_CRAN_INCOMING_: false

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: rstan/rstan

      - uses: r-lib/actions/check-r-package@v2
        with:
          working-directory: rstan/rstan
        env:
          _R_CHECK_CRAN_INCOMING_: false
